<?php

use App\Feed;
use App\User;
use Illuminate\Foundation\Testing\WithoutMiddleware;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Pagination\LengthAwarePaginator;

class FeedsTest extends TestCase
{
    use DatabaseTransactions;
    public $user;
    public function setUp() {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = User::first();
    }

    // @test
    public function test_get_public_feeds() {
        $feeds = Feed::publicShown()->get();

        foreach ($feeds as $feed){
            $this->assertEquals(1, $feed->category->showInPublic);
        }
    }


    // @test
    public function test_get_feeds_in_same_clan() {

        $feeds = Feed::inSameClan($this->user)->get();

        foreach ($feeds as $feed){
            $this->assertEquals($this->user->clan_id, $feed->sender->clan_id);
        }
    }

    public function test_get_front_page_general_feeds() {

        $feeds = Feed::inSameClan($this->user)->topLevelFeeds()->publicShown()->standardFetchSetting($this->user)->paginate(5);

        $this->assertInstanceOf(LengthAwarePaginator::class, $feeds);
    }
}
